cameras:
  - id: "CAM108"
  - id: "CAM109"

image:
  fmt: '.jpg' # Image format
  field: 'image' # Image field name in Redis
  no_img_tracking: 4 # Number of images used to tracking


redis:
  host_name: 'redisedge'
  port: 6379
# redis:
#   host_name: 'localhost'
#   port: 63790

stream:
  target_fps: 25
  maxlen: 2

log:
  verbose: True
  logdir: './logging'  # Inside `logs` folder
  logfile: 'camera_service.log'


speed:
  length_deque: 10
  diff_time: 0.5


time_info:
  timezone: 'Asia/Tokyo'
  strftime_format: '%Y-%m-%d %H:%M:%S.%f'


frames_pool:
  threshold: 15