cameras:
  - id: CAM1
  - id: CAM2
# - id: CAM127
# - id: Gate2Left
# - id: Gate2Right

# model: mode/team1-team2-v2-20231031T181037Z-001/team1-team2-v2/weights/best.pt
# model: yolov11n-pose.pt
model: best_11s.pt
redis:
  HOSTNAME: redisedge
  PORT: 6379
stream:
  STREAMMAXLEN: 2

log:
  verbose: True
  logdir: './logging'
  logfile: 'tracking_service.log'
